apiVersion: apps/v1
kind: Deployment
metadata:
  name: next
  labels:
    app: next
spec:
  replicas: 2
  selector:
    matchLabels:
      app: next
  template:
    metadata:
      labels:
        app: next
    spec:
      containers:
      - name: next
        image: ghcr.io/section/nextdemo:0.0.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: ".1"
            memory: ".1Gi"
          limits:
            cpu: ".1"
            memory: ".1Gi"
        ports:
        - containerPort: 3000
